### PR TITLE
Fixed 'Vote Reward' button labelling, along with several others

### LINKED ISSUE #194: Should say "Claim Vote Reward" instead of "Vote Reward"
On the transaction log it says it correctly - "claim vote reward" but the actual button only says "vote reward"

should say claim vote reward

### PR DESCRIPTION
**Pull request by benzap**
- 'Vote Reward' was changed to 'Claim <dank-logo> Reward'
- 'Challenge Reward' was changed to 'Claim <dank-logo> Reward'
- 'Reclaim Votes' was changed to 'Reclaim <dank-logo> Votes'
- fixes #194 

## Before
dank before

## After
dank after
reclaim after

### CODE REVIEW

**Comment by benzap** [comment]
@madvas wants to approve this before it gets pulled in, just a heads up @fbielejec @jpmonettas

**Comment by jpmonettas** [comment]
Hmm, not sure about the new look, I think I prefer the old one, but not sure

**Comment by madvas** [comment]
I think it's pretty good, we can have it. Just fix one small detail please: In pending state the buttons currently say "Collecting...", change to "Claiming..." for claim reward buttons and "Reclaiming..." for reclaim button

**Comment by benzap** [comment]
image

Added the additional pending messages as suggested by @madvas

**Pull request merged**
