### PR TITLE
Better implementation of flippable tiles with 3d perspective

### PR DESCRIPTION
**Pull request by benzap**
- also added better animation timings, fixed overflow to prevent clipping

### CODE REVIEW

**Comment by benzap** [comment]
fixes #226

**Comment by madvas** [comment]
Could you paste here gif of a card flip please?

**Comment by benzap** [comment]
Flippy tile

I could consider adding even more perspective to it, i'll try some more stuff tomorrow

**Comment by madvas** [comment]
Looks dope, thanks!

**Pull request merged**
