### PR TITLE
Infinite scroll fix 179

### PR DESCRIPTION
**Pull request by benzap**
Re-implemented Infinite Scroll to function more consistently
    - Added additional styling to index.html to get the correct page height
    - Fixed up Dank Registry to work with load function

**Warning** @madvas @jpmonettas 
I might need someone to help me with the dank registry browser page, for some reason it fails to load new values, and it seems to be an issue outside of the infinite scroll component since it is firing correctly.

Every other page works correctly with infinite scroll, so I figured I would make a pull request and get more eyes on the specific problem

### CODE REVIEW

**Comment by benzap** [comment]
Specifically [this spot](https://github.com/district0x/memefactory/pull/246/files#diff-861fb51f3fbefe2addc3c061673b2109R71) always returns true. I figured it was a reaction issue, but it seems to be a bigger problem. My knowledge of the graphql resolvers are a little lacking, so more eyes would appreciated while I continue to try and root out the problem

**Comment by madvas** [comment]
It's still not working properly, in the first gif you can see, it got first 1-2 loads right and after that pretty much same old story. It works ok, if I stop scrolling every time at around ~85% and wait until new memes are added, but as soon as I go ~85%+, it'll never restore from there and just spirals down until all memes are loaded. 

infinite-scroll-bug

In this second gif you can see at the beginning I touch the bottom right at the beginning and it never restores from there. No further scrolling has been done and it loads all memes. This is not desired behaviour. When I touch bottom at the beginning, it should do only 1 load (max 2) and stop there. 

infinite-scroll-bug2

**Comment by benzap** [comment]
Yeah, i'm seeing the same behaviour where it takes you on a wild ride. I'll try some more ideas on how to fix that specifically

**Comment by benzap** [comment]
This problem is a lot more difficult than I originally expected. It might require more interaction between the tiles and the infinite scroll to work correctly.

**Comment by benzap** [comment]
A possible fix is to include a 'load-more' dialog at the bottom and have a infinite scroll event cutoff when it gets close to the bottom. The scrollbar 'pulling' that is occurring is impossible to circumvent. I think a solution might be possible with more coupling between the tiles and the infinite scroll, but this becomes increasingly difficult to implement between different pages.

**Comment by jpmonettas** [comment]
What about rolling back to react-infinite (https://github.com/seatgeek/react-infinite) ?

**Comment by benzap** [comment]
@jpmonettas i'll look into that, it might be the way to go given how painful this is to get working correctly.

**Comment by jpmonettas** [comment]
It was originally working with that component, so they have the same "signature", shouldn't be hard.

**Pull request closed without merging**
