### PR TITLE
Fixed styling on 'Get Dank' page for mobile and tablet devices

### PR DESCRIPTION
**Pull request by benzap**
- fixes issue #341 
# table preview
a
# mobile preview
b

### CODE REVIEW

**Comment by madvas** [comment]
Good, just one more thing, I also mentioned the width of white panel should be the same as submit form. Currently it's narrower.

image

image

**Comment by benzap** [comment]
@madvas 

a

Let me know if you want the title's to match as well, seems to be encroaching at lower dimensions

**Comment by madvas** [comment]
Not sure if you understood, what I was saying before. I was asking to match width of the white panel to white panel of submit form

**Comment by benzap** [comment]
@madvas think I have a better idea, i'll push another fix in a bit

**Comment by benzap** [comment]
@madvas Think I got it this time :)

# Preview
get dank

**Comment by madvas** [comment]
Cool, that looks better, thank you

**Pull request merged**
